### PR TITLE
Gen2 58 feature/migrate home page

### PR DESCRIPTION
**Pull request by JanukanS**
[Feature] GEN2-58: Frontend Migrating: Home Page

This PR re-implements the HomeView within the mobile views as a component for the web implementation of iCard. 
This involved partial recreation of the mobile implementation's directory structure for the web implementation (i.e. Components and Views folders within src, migration of assets). Removal of some API functionality within the home page as it has not been implemented yet for the web view. Some components required for home page and other components (Vendor Card/List) have been imported from react-native-web instead of the associated react-native packages (i.e. ScrollView).

### CODE REVIEW

**Comment by PaulHo0501** [comment]
Hi Janukan! Please resolve the merge conflicts on your end so that I can merge your code in! Thanks

**Comment by JanukanS** [comment]
Should be good to merge now

**Comment by PaulHo0501** [comment]
LGTM!

**Review by PaulHo0501 — APPROVED** [review]
LGTM

**Pull request merged**
