### PR TITLE
Feature #62: Create an express API that connects to MongoDB

### PR DESCRIPTION
**Pull request by ArmaanKatyal**
In this pull request, I have done the following:
- created backend folder in the ICard repo including standard libraries like prettier and eslint
- skeletal files that connect to MongoDB
- test infrastructure with a sample test to test the DB connection

### CODE REVIEW

**Comment by dimassudjito** [comment]
@ArmaanKatyal just need to add jest to eslint config so it doesn't complain in test files (see the old PR for more details)

**Comment by dimassudjito** [comment]
@ArmaanKatyal also please change the default port number to other than 3000, since we might use 3000 for react e.g., 8000

**Comment by ArmaanKatyal** [comment]
hey, @dimassudjito you can now merge this pull request. I think I have fixed all the issues that you mentioned. If there are any more changes let me know.

**Review by dimassudjito — APPROVED** [review]
Yes of course, sorry for the delay, I've been occupied by the project scoping meeting and writing requirements for the ICard project

**Pull request merged**
