### PR TITLE
Added mock server data and re-introduced navigation code

### PR DESCRIPTION
**Pull request by JanukanS**
1. Vendor Data is now pulled from a server (URL obtained from environment variables)
2. Previous mock vendor data json file is now used when data cannot be obtained from server
3. Re-introduced navigation code, MyIcard view and Registration view are displayed based on the user state

### CODE REVIEW

**Comment by JanukanS** [comment]
Potential Issue:
Populating the Vendor Data seems to be done only at "build" time. If the web app is built while not connected to the internet, 
data from the json file will be loaded (as expected). But reconnecting to the internet and refreshing the page does not update the vendor data. The following are steps for replication

1. Disconnect from the internet
2. Build the application and open to see offline json data
3. Reconnect to internet
4. Refresh page
5. vendor should be updated but still displays offline json data

**Comment by PaulHo0501** [comment]
> Potential Issue: Populating the Vendor Data seems to be done only at "build" time. If the web app is built while not connected to the internet, data from the json file will be loaded (as expected). But reconnecting to the internet and refreshing the page does not update the vendor data. The following are steps for replication
> 
> 1. Disconnect from the internet
> 2. Build the application and open to see offline json data
> 3. Reconnect to internet
> 4. Refresh page
> 5. vendor should be updated but still displays offline json data

This comes from the useEffect be used to fetch only runs for one initial render. We may want to have "swipe to refresh" later in the future. For now, can we catch the no connection error and just not populate the page?

**Comment by PaulHo0501** [comment]
Thanks! Please fix the merge conflicts and I will merge your code!

**Review by PaulHo0501 — APPROVED** [review]
LGTM!

**Pull request merged**
