### PR TITLE
Feature/96

### PR DESCRIPTION
**Pull request by TienDucHo**
In this PR I have:
- Cleaned up the unnecessary package while using expo
- Changed the package name from "com.llamoss0501." to "org.uofablueprint"
- Added new runtime script for the package.json to use expo
- Rewritten the README file to have instructions on how to run expo

### CODE REVIEW

**Review by dimassudjito — COMMENTED** [review]
All the changes look good, though I'm having trouble running the expo script: 
image

Any idea why?

**Comment by TienDucHo** [comment]
> All the changes look good, though I'm having trouble running the expo script: image
> 
> Any idea why? @TienDucHo

You should run npm install to reinstall the packages first due to some removal of some unnecessary packages

**Comment by dimassudjito** [comment]
I did fresh git clone of ICard and the problem persists. Is the problem that "react-native-vision-camera" is deleted but the scanner page still use it? or is it something else?

**Comment by TienDucHo** [comment]
This is the one causing the error mobile/app.json

The plugin is needed to be deleted. I will commit a new fix asap

**Comment by TienDucHo** [comment]
> I did fresh git clone of ICard and the problem persists. Is the problem that "react-native-vision-camera" is deleted but the scanner page still use it? or is it something else?

Fixed with [ec22e0d](https://github.com/UofA-Blueprint/ICard/pull/13/commits/ec22e0d8d92372a7de04a5584aa890cc9f15d20b)

**Review by dimassudjito — APPROVED** [review]

**Pull request merged**
