### PR TITLE
Feature/135: Navigation Flow from Authentication to My ICard Page

### PR DESCRIPTION
**Pull request by PaulHo0501**
In this PR I have:
- Hooked up the My ICard Page to display after the user signed in with Google
- Sent the ID Token gotten from Google to the backend for verification
- Displayed the User data in the My ICard Page accordingly

### CODE REVIEW

**Review by dimassudjito — CHANGES_REQUESTED** [review]
I'm having a problem making the API call. Could you rebase this branch to the latest develop? You will also need to add x-api-key to the request header since the route endpoint now asks for this

**Comment by TienDucHo** [comment]
> a

Rewrite the authentication to use the environment variable as followed 
``` API_ROUTE=https://icard-stag.herokuapp.com/
API_KEY=test
CLIENT_ID=71633949714-fdu0efehl8ouvbih6eosrgfla2b2mk0u.apps.googleusercontent.com  ```

Fixed merge conflict with develop

**Review by dimassudjito — CHANGES_REQUESTED** [review]
It's working nicely now! We just need to hide the env file and we'll merge this

**Comment by TienDucHo** [comment]
Removed .env and added .env to gitignore

**Pull request merged**
