### PR TITLE
Feature/161: Remove Scan View

### PR DESCRIPTION
**Pull request by kunaal-gupta**
Remove Scan View from codebase

### CODE REVIEW

**Comment by dimassudjito** [comment]
Please use "develop" branch as pull request target next time instead of "main" branch

**Review by MoyinF — CHANGES_REQUESTED** [review]
It seems a lot of the features of the develop branch are not available here. Did you remember to pull the most recent version of the develop branch? (It's most likely because your target was previously main). Integrate the develop branch and fix any possible conflicts.

**Review by yismailuofa — APPROVED** [review]
Besides comments LGTM,
Please add a description saying why we decided to remove this view.

**Comment by yismailuofa** [comment]
@MoyinF 
Updated the title as well, if it looks good approve and merge?

**Pull request merged**
